
ccdn_forum_moderator_topic_close:
    path: /{topicId}/close
    defaults: { _controller: CCDNForumForumBundle:ModeratorTopic:close, _locale: de, forumName: "Forum" }

ccdn_forum_moderator_topic_reopen:
    path: /{topicId}/reopen
    defaults: { _controller: CCDNForumForumBundle:ModeratorTopic:reopen, _locale: de, forumName: "Forum" }

ccdn_forum_moderator_topic_sticky:
    path: /{topicId}/sticky
    defaults: { _controller: CCDNForumForumBundle:ModeratorTopic:sticky, _locale: de, forumName: "Forum" }

ccdn_forum_moderator_topic_unsticky:
    path: /{topicId}/unsticky
    defaults: { _controller: CCDNForumForumBundle:ModeratorTopic:unsticky, _locale: de, forumName: "Forum" }

ccdn_forum_moderator_topic_delete:
    path: /{topicId}/delete
    defaults: { _controller: CCDNForumForumBundle:ModeratorTopic:delete, _locale: de, forumName: "Forum" }

ccdn_forum_moderator_topic_delete_process:
    path: /{topicId}/delete/process
    defaults: { _controller: CCDNForumForumBundle:ModeratorTopic:deleteProcess, _locale: de, forumName: "Forum" }

ccdn_forum_moderator_topic_restore:
    path: /{topicId}/restore
    defaults: { _controller: CCDNForumForumBundle:ModeratorTopic:restore, _locale: de, forumName: "Forum" }

ccdn_forum_moderator_topic_change_board:
    path: /{topicId}/change-board
    defaults: { _controller: CCDNForumForumBundle:ModeratorTopic:changeBoard, _locale: de, forumName: "Forum" }

ccdn_forum_moderator_topic_change_board_process:
    path: /{topicId}/change-board/process
    defaults: { _controller: CCDNForumForumBundle:ModeratorTopic:changeBoardProcess, _locale: de, forumName: "Forum" }
