
#ccdn_forum_user_category_index:
#    pattern: /index
#    defaults: { _controller: CCDNForumForumBundle:UserCategory:index, _locale: de, forumName: "Forum" }

ccdn_forum_user_category_index:
    path:     /
    defaults: { _controller: CCDNForumForumBundle:UserCategory:index, _locale: de, forumName: "Forum" }

ccdn_forum_user_category_show:
    path:     /category/{categoryId}
    defaults: { _controller: CCDNForumForumBundle:UserCategory:show, _locale: de, forumName: "Forum" }
