
#
# CRUD
#
ccdn_forum_user_topic_show:
    path: /{topicId}
    defaults: { _controller: CCDNForumForumBundle:UserTopic:show, _locale: de, forumName: "Forum" }

ccdn_forum_user_topic_create:
    path: /create/for-board/{boardId}
    defaults: { _controller: CCDNForumForumBundle:UserTopic:create, _locale: de, forumName: "Forum" }

ccdn_forum_user_topic_create_process:
    path: /create/for-board/{boardId}/process
    defaults: { _controller: CCDNForumForumBundle:UserTopic:createProcess, _locale: de, forumName: "Forum" }

ccdn_forum_user_topic_reply:
    path: /{topicId}/reply
    defaults: { _controller: CCDNForumForumBundle:UserTopic:reply, _locale: de, forumName: "Forum" }

ccdn_forum_user_topic_reply_process:
    path: /{topicId}/reply/process
    defaults: { _controller: CCDNForumForumBundle:UserTopic:replyProcess, _locale: de, forumName: "Forum" }
