#
# CRUD
#
ccdn_forum_user_post_show:
    path: /{postId}
    defaults: { _controller: CCDNForumForumBundle:UserPost:show, _locale: de, forumName: "Forum" }

ccdn_forum_user_post_edit:
    path: /{postId}/edit
    defaults: { _controller: CCDNForumForumBundle:UserPost:edit, _locale: de, forumName: "Forum" }

ccdn_forum_user_post_edit_process:
    path: /{postId}/edit/process
    defaults: { _controller: CCDNForumForumBundle:UserPost:editProcess, _locale: de, forumName: "Forum" }

ccdn_forum_user_post_delete:
    path: /{postId}/delete
    defaults: { _controller: CCDNForumForumBundle:UserPost:delete, _locale: de, forumName: "Forum" }

ccdn_forum_user_post_delete_process:
    path: /{postId}/delete/process
    defaults: { _controller: CCDNForumForumBundle:UserPost:deleteProcess, _locale: de, forumName: "Forum" }
